package com.musicsocial.session.service

import com.musicsocial.session.domain.model.*
import com.musicsocial.session.repository.RoomRepository
import org.springframework.stereotype.Service
import java.time.Instant
import java.util.*

@Service
class RoomService(
    private val roomRepository: RoomRepository
) {
    
    fun createRoom(roomId: String): RoomState {
        // Check if room already exists
        val existing = roomRepository.findByRoomId(roomId).orElse(null)
        if (existing != null) {
            return existing
        }
        
        val room = RoomState(
            id = null, // Will be generated by MongoDB
            roomId = roomId,
            currentTrack = null,
            position = 0.0,
            isPlaying = false,
            participants = emptyList(),
            queue = emptyList(),
            lastAction = null,
            createdAt = Instant.now(),
            updatedAt = Instant.now()
        )
        return roomRepository.save(room)
    }
    
    fun getRoom(roomId: String): RoomState? {
        return roomRepository.findByRoomId(roomId).orElse(null)
    }
    
    fun getOrCreateRoom(roomId: String): RoomState {
        return getRoom(roomId) ?: createRoom(roomId)
    }
    
    fun addParticipant(roomId: String, userId: String, username: String): RoomState {
        val room = getOrCreateRoom(roomId)
        val participant = Participant(
            userId = userId,
            username = username,
            isOnline = true,
            joinedAt = Instant.now()
        )
        
        val existingIndex = room.participants.indexOfFirst { it.userId == userId }
        val updatedParticipants = if (existingIndex >= 0) {
            room.participants.toMutableList().apply {
                this[existingIndex] = participant.copy(isOnline = true)
            }
        } else {
            room.participants + participant
        }
        
        val updatedRoom = room.copy(
            id = room.id, // Preserve the MongoDB id
            participants = updatedParticipants,
            updatedAt = Instant.now()
        )
        
        return roomRepository.save(updatedRoom)
    }
    
    fun removeParticipant(roomId: String, userId: String): RoomState? {
        val room = getRoom(roomId) ?: return null
        
        val updatedParticipants = room.participants.map { p ->
            if (p.userId == userId) p.copy(isOnline = false) else p
        }
        
        val updatedRoom = room.copy(
            id = room.id, // Preserve the MongoDB id
            participants = updatedParticipants,
            updatedAt = Instant.now()
        )
        
        return roomRepository.save(updatedRoom)
    }
    
    fun updateRoomState(roomId: String, updateFn: (RoomState) -> RoomState): RoomState? {
        val room = getRoom(roomId) ?: return null
        val updatedRoom = updateFn(room).copy(
            id = room.id, // Preserve the MongoDB id
            updatedAt = Instant.now()
        )
        return roomRepository.save(updatedRoom)
    }
    
    fun deleteRoom(roomId: String) {
        val room = getRoom(roomId)
        room?.let { roomRepository.delete(it) }
    }
}

